"""empty message

Revision ID: 49f2f3b90367
Revises: a4bf2a53273e
Create Date: 2016-04-19 10:50:18.709927

"""

# revision identifiers, used by Alembic.
revision = '49f2f3b90367'
down_revision = 'a4bf2a53273e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_entry', 'user', ['author_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    ### end Alembic commands ###
