"""empty message

Revision ID: 7ffba264c1e8
Revises: 49f2f3b90367
Create Date: 2016-05-05 11:23:46.988788

"""

# revision identifiers, used by Alembic.
revision = '7ffba264c1e8'
down_revision = '49f2f3b90367'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    ### end Alembic commands ###
