"""empty message

Revision ID: 809417be4ac2
Revises: a4bf2a53273e
Create Date: 2016-04-18 23:31:25.435424

"""

# revision identifiers, used by Alembic.
revision = '809417be4ac2'
down_revision = 'a4bf2a53273e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'entry', 'user', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    ### end Alembic commands ###
